// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHocAPI.AppDBContexxt;

#nullable disable

namespace QuanLyKhoaHocAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231221024333_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.BaiViet", b =>
                {
                    b.Property<int>("BaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaiVietID"));

                    b.Property<int?>("ChuDeID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungNgan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<string>("TenBaiViet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTacGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("BaiVietID");

                    b.HasIndex("ChuDeID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.ChuDe", b =>
                {
                    b.Property<int>("ChuDeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuDeID"));

                    b.Property<int?>("LoaiBaiVietID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChuDeID");

                    b.HasIndex("LoaiBaiVietID");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.DangKiHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaybatDau")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaiKhoanID")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrangHocID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("KhoaHocID");

                    b.HasIndex("TaiKhoanID");

                    b.HasIndex("TinhTrangHocID");

                    b.ToTable("DangKiHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.HocVien", b =>
                {
                    b.Property<int>("HocVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocVienID"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HocVienID");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaHocID"));

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HocPhi")
                        .HasColumnType("real");

                    b.Property<int?>("LoaiKhoaHocID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMon")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.HasKey("KhoaHocID");

                    b.HasIndex("LoaiKhoaHocID");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.LoaiBaiViet", b =>
                {
                    b.Property<int>("LoaiBaiVietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiBaiVietID"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoaiBaiVietID");

                    b.ToTable("LoaiBaiViets");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("LoaiKhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiKhoaHocID"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("LoaiKhoaHocID");

                    b.ToTable("LoaiKhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.QuyenHan", b =>
                {
                    b.Property<int>("QuyenHanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenHanID"));

                    b.Property<string>("TenQuyenHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuyenHanID");

                    b.ToTable("QuyenHans");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QuyenHanId")
                        .HasColumnType("int");

                    b.Property<string>("Tai_Khoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("QuyenHanId");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.TinhTrangHoc", b =>
                {
                    b.Property<int>("TinhTrangHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TinhTrangHocID"));

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TinhTrangHocID");

                    b.ToTable("TinhTrangHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.BaiViet", b =>
                {
                    b.HasOne("QuanLyKhoaHocAPI.Entity.ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("ChuDeID");

                    b.HasOne("QuanLyKhoaHocAPI.Entity.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID");

                    b.Navigation("ChuDe");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.ChuDe", b =>
                {
                    b.HasOne("QuanLyKhoaHocAPI.Entity.LoaiBaiViet", "LoaiBaiViet")
                        .WithMany()
                        .HasForeignKey("LoaiBaiVietID");

                    b.Navigation("LoaiBaiViet");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.DangKiHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHocAPI.Entity.HocVien", "HocVien")
                        .WithMany("DangKiHocs")
                        .HasForeignKey("HocVienID");

                    b.HasOne("QuanLyKhoaHocAPI.Entity.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocID");

                    b.HasOne("QuanLyKhoaHocAPI.Entity.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanID");

                    b.HasOne("QuanLyKhoaHocAPI.Entity.TinhTrangHoc", "TinhTrangHoc")
                        .WithMany()
                        .HasForeignKey("TinhTrangHocID");

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TinhTrangHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.KhoaHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHocAPI.Entity.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany()
                        .HasForeignKey("LoaiKhoaHocID");

                    b.Navigation("LoaiKhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoaHocAPI.Entity.QuyenHan", "QuyenHans")
                        .WithMany()
                        .HasForeignKey("QuyenHanId");

                    b.Navigation("QuyenHans");
                });

            modelBuilder.Entity("QuanLyKhoaHocAPI.Entity.HocVien", b =>
                {
                    b.Navigation("DangKiHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
